[project]
name = "portfoliobuilder"
version = "1.0.0"
description = "Investment portfolio builder application"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "polars>=1.16.0",
    "pydantic>=2.10.3",
    "pydantic-settings>=2.6.1",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
    "fastapi>=0.115.6",
    "uvicorn[standard]>=0.32.1",
]

[project.optional-dependencies]
ui = [
    "streamlit>=1.40.2",
]

[tool.uv]
package = false
dev-dependencies = [
    "coverage>=7.6.9",
    "httpx>=0.28.1",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "tqdm>=4.67.1",
    "trio>=0.27.0",
]

[tool.pytest.ini_options]
addopts = [
  "--strict-config",
  "--strict-markers",
]
xfail_strict = true
junit_family = "xunit2"

[tool.coverage.html]
show_contexts = true

[tool.coverage.report]
show_missing = true
sort = "-Cover"

[tool.coverage.run]
source = [
    "app",
    "tests",
]

[tool.ruff]
line-length = 108
fix = true

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "D", # pydocstyle
  "D213", # Multi-line docstring summary should start at the second line
  "D417", # Missing argument descriptions
  "E", # pycodestyle
  "EM", # flake8-errmsg
  "F", # Pyflakes
  "FBT", # flake8-boolean-trap
  "I", # isort
  "PIE", # flake8-pie
  "PT", # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "SIM", # flake8-simplify
  "TID", # flake8-tidy-imports
  "TRY", # tryceratops
  "UP", # pyupgrade
  "W", # pycodestyle
]
ignore = [
  # pydocstyle: http://www.pydocstyle.org/en/stable/error_codes.html
  "D401", # Relax NumPy docstring convention: First line should be in imperative mood
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.pycodestyle]
max-doc-length = 108

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
files = ["app"]
strict = true
enable_error_code = [
  "redundant-expr",
  "truthy-bool",
  "ignore-without-code",
]
disallow_subclassing_any = false
disallow_untyped_decorators = false
plugins = "pydantic.mypy"

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
