name: Docker Build & Artifact Registry Push

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: gcloud docker config
        run: gcloud auth configure-docker ${{ vars.HOSTNAME_LIST }}
      - name: Delete previous image #Images are ~266MB, free tier hosting is 500MB
        run: yes Y | gcloud artifacts docker images delete ${{ vars.HOSTNAME_LIST }}/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:${{ vars.TAG }}
      - name: Build
        run: docker build -t ${{ vars.IMAGE }}:${{ vars.TAG }} .
      - name: Tag
        run: docker tag ${{ vars.IMAGE }}:${{ vars.TAG }} ${{ vars.HOSTNAME_LIST }}/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:${{ vars.TAG }}
      - name: Push image
        run: docker push ${{ vars.HOSTNAME_LIST }}/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:${{ vars.TAG }}
