name: Cloud Run Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.SERVICE }} \
            --image=${{ vars.HOSTNAME_LIST }}/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:${{ vars.TAG }} \
            --port=${{ vars.PORT }} \
            --cpu=${{ vars.CPU }} \
            --memory=${{ vars.MEMORY }} \
            --concurrency=${{ vars.CONCURRENCY }} \
            --min-instances=${{ vars.MIN_INSTANCES }} \
            --max-instances=${{ vars.MAX_INSTANCES }} \
            --timeout=${{ vars.TIMEOUT }} \
            --no-cpu-boost \
            --region=${{ vars.REGION }} \
            --project=${{ vars.PROJECT_ID }} \
            && gcloud run services update-traffic ${{ vars.SERVICE }} --to-latest --region=${{ vars.REGION }}
